### ISSUE TITLE
IRONIC_EXTERNAL_IP is ignored

### ISSUE THREAD

**Issue by mossad-zika** [metal3-io/ironic-image#551]
Hello, I am new to metal3

I am trying to configure BareMetal + metal3 exactly by https://book.metal3.io/quick-start instruction

It looks like `IRONIC_EXTERNAL_IP` is not working because my server tries to boot over POD's IP

Please help

<img width="708" alt="Screenshot 2024-09-02 at 19 45 55" src="https://github.com/user-attachments/assets/33d0f97d-36a3-4a9b-accf-2128d7405f5e">

I am using baremetal-operator 0.6.1 and ironic v26.0.0

BTW I had to create a file like this `boot.ipxe` (which somehow not mention in the instruction)

```
#!ipxe
set server-ip 10.188.49.74
goto ironic

:ironic
chain http://${server-ip}:6180/boot.ipxe
```

My guess of root cause: ENV is ignored in https://github.com/metal3-io/ironic-ipa-downloader/blob/main/get-resource.sh

**Comment by tuminoid** [comment]
@dtantsur @Rozzii

**Comment by dtantsur** [comment]
> IRONIC_EXTERNAL_IP suppose to do then 

IRONIC_EXTERNAL_IP is only used for virtual media deployments, while you're using network boot.

> I had to create a file like this boot.ipxe (which somehow not mention in the instruction)

It is not mentioned because it is not required: the actual issue is missing HTTP_PORT configuration: https://github.com/metal3-io/metal3-docs/pull/470

> why IRONIC_IP not mentioned in the QuickStart guide

Quick start might have an unusual networking, regular deployments rarely need to set it.

**Comment by Rozzii** [comment]
This resulted in an actual fix https://github.com/metal3-io/metal3-docs/pull/470 so I will accept the issue
/triage accepted
